// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPrompter creates a new instance of MockPrompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrompter {
	mock := &MockPrompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrompter is an autogenerated mock type for the Prompter type
type MockPrompter struct {
	mock.Mock
}

type MockPrompter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrompter) EXPECT() *MockPrompter_Expecter {
	return &MockPrompter_Expecter{mock: &_m.Mock}
}

// Confirm provides a mock function for the type MockPrompter
func (_mock *MockPrompter) Confirm(label string, defaultValue bool) (bool, error) {
	ret := _mock.Called(label, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) (bool, error)); ok {
		return returnFunc(label, defaultValue)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool) bool); ok {
		r0 = returnFunc(label, defaultValue)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = returnFunc(label, defaultValue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrompter_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type MockPrompter_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - label string
//   - defaultValue bool
func (_e *MockPrompter_Expecter) Confirm(label any, defaultValue any) *MockPrompter_Confirm_Call {
	return &MockPrompter_Confirm_Call{Call: _e.mock.On("Confirm", label, defaultValue)}
}

func (_c *MockPrompter_Confirm_Call) Run(run func(label string, defaultValue bool)) *MockPrompter_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPrompter_Confirm_Call) Return(b bool, err error) *MockPrompter_Confirm_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPrompter_Confirm_Call) RunAndReturn(run func(label string, defaultValue bool) (bool, error)) *MockPrompter_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// MultiSelect provides a mock function for the type MockPrompter
func (_mock *MockPrompter) MultiSelect(label string, options []string, preChecked []string) ([]string, error) {
	ret := _mock.Called(label, options, preChecked)

	if len(ret) == 0 {
		panic("no return value specified for MultiSelect")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []string, []string) ([]string, error)); ok {
		return returnFunc(label, options, preChecked)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string, []string) []string); ok {
		r0 = returnFunc(label, options, preChecked)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string, []string) error); ok {
		r1 = returnFunc(label, options, preChecked)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrompter_MultiSelect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MultiSelect'
type MockPrompter_MultiSelect_Call struct {
	*mock.Call
}

// MultiSelect is a helper method to define mock.On call
//   - label string
//   - options []string
//   - preChecked []string
func (_e *MockPrompter_Expecter) MultiSelect(label any, options any, preChecked any) *MockPrompter_MultiSelect_Call {
	return &MockPrompter_MultiSelect_Call{Call: _e.mock.On("MultiSelect", label, options, preChecked)}
}

func (_c *MockPrompter_MultiSelect_Call) Run(run func(label string, options []string, preChecked []string)) *MockPrompter_MultiSelect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPrompter_MultiSelect_Call) Return(strings []string, err error) *MockPrompter_MultiSelect_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockPrompter_MultiSelect_Call) RunAndReturn(run func(label string, options []string, preChecked []string) ([]string, error)) *MockPrompter_MultiSelect_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type MockPrompter
func (_mock *MockPrompter) Select(label string, options []string, defaultOption string) (int, string, error) {
	ret := _mock.Called(label, options, defaultOption)

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 int
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, []string, string) (int, string, error)); ok {
		return returnFunc(label, options, defaultOption)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string, string) int); ok {
		r0 = returnFunc(label, options, defaultOption)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string, string) string); ok {
		r1 = returnFunc(label, options, defaultOption)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string, []string, string) error); ok {
		r2 = returnFunc(label, options, defaultOption)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPrompter_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type MockPrompter_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - label string
//   - options []string
//   - defaultOption string
func (_e *MockPrompter_Expecter) Select(label any, options any, defaultOption any) *MockPrompter_Select_Call {
	return &MockPrompter_Select_Call{Call: _e.mock.On("Select", label, options, defaultOption)}
}

func (_c *MockPrompter_Select_Call) Run(run func(label string, options []string, defaultOption string)) *MockPrompter_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPrompter_Select_Call) Return(n int, s string, err error) *MockPrompter_Select_Call {
	_c.Call.Return(n, s, err)
	return _c
}

func (_c *MockPrompter_Select_Call) RunAndReturn(run func(label string, options []string, defaultOption string) (int, string, error)) *MockPrompter_Select_Call {
	_c.Call.Return(run)
	return _c
}

// Text provides a mock function for the type MockPrompter
func (_mock *MockPrompter) Text(label string, mask string, defaultValue string) (string, error) {
	ret := _mock.Called(label, mask, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for Text")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return returnFunc(label, mask, defaultValue)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(label, mask, defaultValue)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(label, mask, defaultValue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrompter_Text_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Text'
type MockPrompter_Text_Call struct {
	*mock.Call
}

// Text is a helper method to define mock.On call
//   - label string
//   - mask string
//   - defaultValue string
func (_e *MockPrompter_Expecter) Text(label any, mask any, defaultValue any) *MockPrompter_Text_Call {
	return &MockPrompter_Text_Call{Call: _e.mock.On("Text", label, mask, defaultValue)}
}

func (_c *MockPrompter_Text_Call) Run(run func(label string, mask string, defaultValue string)) *MockPrompter_Text_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPrompter_Text_Call) Return(s string, err error) *MockPrompter_Text_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPrompter_Text_Call) RunAndReturn(run func(label string, mask string, defaultValue string) (string, error)) *MockPrompter_Text_Call {
	_c.Call.Return(run)
	return _c
}
