// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockValueSource creates a new instance of MockValueSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValueSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValueSource {
	mock := &MockValueSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValueSource is an autogenerated mock type for the ValueSource type
type MockValueSource struct {
	mock.Mock
}

type MockValueSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValueSource) EXPECT() *MockValueSource_Expecter {
	return &MockValueSource_Expecter{mock: &_m.Mock}
}

// EnvFile provides a mock function for the type MockValueSource
func (_mock *MockValueSource) EnvFile(key string) (string, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for EnvFile")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockValueSource_EnvFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvFile'
type MockValueSource_EnvFile_Call struct {
	*mock.Call
}

// EnvFile is a helper method to define mock.On call
//   - key string
func (_e *MockValueSource_Expecter) EnvFile(key any) *MockValueSource_EnvFile_Call {
	return &MockValueSource_EnvFile_Call{Call: _e.mock.On("EnvFile", key)}
}

func (_c *MockValueSource_EnvFile_Call) Run(run func(key string)) *MockValueSource_EnvFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockValueSource_EnvFile_Call) Return(value string, ok bool) *MockValueSource_EnvFile_Call {
	_c.Call.Return(value, ok)
	return _c
}

func (_c *MockValueSource_EnvFile_Call) RunAndReturn(run func(key string) (string, bool)) *MockValueSource_EnvFile_Call {
	_c.Call.Return(run)
	return _c
}

// Flag provides a mock function for the type MockValueSource
func (_mock *MockValueSource) Flag(name string) (string, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Flag")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockValueSource_Flag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flag'
type MockValueSource_Flag_Call struct {
	*mock.Call
}

// Flag is a helper method to define mock.On call
//   - name string
func (_e *MockValueSource_Expecter) Flag(name any) *MockValueSource_Flag_Call {
	return &MockValueSource_Flag_Call{Call: _e.mock.On("Flag", name)}
}

func (_c *MockValueSource_Flag_Call) Run(run func(name string)) *MockValueSource_Flag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockValueSource_Flag_Call) Return(value string, set bool) *MockValueSource_Flag_Call {
	_c.Call.Return(value, set)
	return _c
}

func (_c *MockValueSource_Flag_Call) RunAndReturn(run func(name string) (string, bool)) *MockValueSource_Flag_Call {
	_c.Call.Return(run)
	return _c
}
